schema_version = "1.0.0"

id = "mysims_blender"
version = "0.1.2"
name = "Mysims Blender"
tagline = "Import and export MySims Windows models"
maintainer = "ThuverX"
type = "add-on"
tags = ["Modeling", "Import-Export"]

blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]